woowa-techcamp-2022/android-banchan-07

- data/src/main/java/com/woowahan/ordering/data/local/dao/CartDao.kt
- data/src/main/java/com/woowahan/ordering/data/local/dao/OrderDao.kt
- data/src/main/java/com/woowahan/ordering/data/local/dao/RecentlyDao.kt
- close #10 
- 누락된 주문내역 요약 조회 쿼리 추가
- 쿼리 결과를 배달 요청시각 최신순으로 정렬
- 메서드 간 공백 추가
- 불필요한 임포트 제거
> [FIX] 주문내역 테이블 DAO 누락된 쿼리 추가

- presentation/src/main/java/com/woowahan/ordering/ui/adapter/home/CountAndFilterAdapter.kt
- presentation/src/main/java/com/woowahan/ordering/ui/adapter/home/FilterAdapter.kt
- Soup, Side 화면
- close #27
- Spinner 선택과 동시에 초기값으로 재설정되는 버그
##Task
- Spinner Adapter의 변수에 생성된 객체가 존재하지 않을 때만 객체 생성
> [FIX] #27 - Spinner Adapter의 변수에 생성된 객체가 존재하지 않을 때만 객체 생성

- presentation/src/main/res/layout/item_food_linear.xml
- 메인요리
- close #33 
- 리니어타입일 때 판매가 컨스트레인트 깨짐 수정
- 판매가의 marginStart 를 할인율의 marginEnd 로 이동
> [FIX] 리니어타입일 때 판매가 컨스트레인트 깨짐 수정

- presentation/src/main/res/layout/item_food_grid.xml
- presentation/src/main/res/layout/item_food_linear.xml
- presentation/src/main/res/values-night/themes.xml
- presentation/src/main/res/values/themes.xml
- closes #44
- RecyclerView Item, Theme
- Theme Text Bold 버전의 텍스트가 볼드처리 되지 않는 것
- 리사이클러뷰 아이템의 제목이 Bold처리 되지 않는 것
- Theme에 등록된 Bold 스타일의 android:fontWeight가 아닌 android:textStyle 태그 값을 "bold"로 바꿈
- 리사이클러뷰의 아이템 제목의 스타일을 Body2.Bold로 수정
> [FIX] #44 - Themes

- data/src/main/java/com/woowahan/ordering/data/local/dao/CartDao.kt
- domain/src/main/java/com/woowahan/ordering/domain/model/Cart.kt
- presentation/src/main/java/com/woowahan/ordering/ui/UiState.kt
- presentation/src/main/java/com/woowahan/ordering/ui/adapter/home/BestFoodAdapter.kt
- presentation/src/main/java/com/woowahan/ordering/ui/adapter/home/FoodAdapter.kt
- presentation/src/main/java/com/woowahan/ordering/ui/adapter/viewholder/ItemFoodBestViewHolder.kt
- presentation/src/main/java/com/woowahan/ordering/ui/adapter/viewholder/ItemFoodViewHolder.kt
- presentation/src/main/java/com/woowahan/ordering/ui/dialog/CartBottomSheet.kt
- presentation/src/main/java/com/woowahan/ordering/ui/dialog/CartDialogFragment.kt
- presentation/src/main/java/com/woowahan/ordering/ui/fragment/home/best/BestFragment.kt
- presentation/src/main/java/com/woowahan/ordering/ui/fragment/home/main/MainDishFragment.kt
- presentation/src/main/java/com/woowahan/ordering/ui/fragment/home/other/OtherDishFragment.kt
- presentation/src/main/java/com/woowahan/ordering/ui/viewmodel/CartBottomSheetViewModel.kt
- presentation/src/main/res/layout/bottom_sheet_cart.xml
- presentation/src/main/res/layout/item_food_grid.xml
- presentation/src/main/res/values/strings.xml
- presentation/src/main/res/values/style_rounded_dialog.xml
- 장바구니, 메인 화면
- close #38 
- 장바구니 바텀시트에 아이템 데이터를 연결했습니다.
- 장바구니에 담기 버튼을 누르면 카트 테이블 갱신 후 다이얼로그를 띄웁니다.
- 장바구니에 담긴 아이템은 버튼 상태가 변경되도록 했습니다.
- 기존에 장바구니에 들어있던 아이템도 버튼 상태가 선택된 채로 나타나도록 쿼리를 수정했습니다!
```kotlin
// 변경 전
@Query("SELECT * FROM Cart WHERE orderId = null")
fun getCart(): List<CartEntity>
// 변경 후
@Query("SELECT * FROM Cart WHERE orderId is null")
fun getCart(): List<CartEntity>
```
<p align="center">
</p>
> [FEAT] 장바구니 바텀시트 데이터 연결

- presentation/src/main/java/com/woowahan/ordering/ui/adapter/home/CountAndFilterAdapter.kt
- OtherDishFragment
- close #50
- Spinner가 작동하지 않는 버그
- notifyDataSetChanged()로 인한 Spinner의 Adapter가 초기화되어 상태가 reset되는 버그 수정
> [FIX] #50 - 스피너 초기화 현상

- domain/src/main/java/com/woowahan/ordering/domain/model/CartListItem.kt
- presentation/src/main/java/com/woowahan/ordering/ui/activity/MainActivity.kt
- presentation/src/main/java/com/woowahan/ordering/ui/adapter/DiffUtils.kt
- presentation/src/main/java/com/woowahan/ordering/ui/adapter/cart/CartAdapter.kt
- presentation/src/main/java/com/woowahan/ordering/ui/adapter/cart/CartRecentlyAdapter.kt
- presentation/src/main/java/com/woowahan/ordering/ui/adapter/cart/RecentlyAdapter.kt
- presentation/src/main/java/com/woowahan/ordering/ui/dialog/CartDialogFragment.kt
- presentation/src/main/java/com/woowahan/ordering/ui/fragment/cart/CartFragment.kt
- presentation/src/main/java/com/woowahan/ordering/ui/fragment/home/HomeFragment.kt
- presentation/src/main/java/com/woowahan/ordering/ui/fragment/home/best/BestFragment.kt
- presentation/src/main/java/com/woowahan/ordering/ui/viewmodel/CartViewModel.kt
- presentation/src/main/res/layout/activity_main.xml
- presentation/src/main/res/layout/fragment_cart.xml
- 장바구니
- close #54 
- 장바구니 화면에서 장바구니 목록과 최근 본 상품 목록을 보여줍니다.
- 메인 화면에서도 장바구니 화면으로 이동할 수 있고, 툴바도 알맞게 변경되도록 했습니다.
> [FEAT] 장바구니 목록 기능 구현

- data/src/main/java/com/woowahan/ordering/data/mapper/RecentlyMapper.kt
- domain/src/main/java/com/woowahan/ordering/domain/model/Recently.kt
- domain/src/main/java/com/woowahan/ordering/domain/usecase/recently/GetRecentlyUseCase.kt
- presentation/src/main/java/com/woowahan/ordering/di/usecase/RecentlyUseCaseModule.kt
- presentation/src/main/java/com/woowahan/ordering/ui/activity/MainActivity.kt
- presentation/src/main/java/com/woowahan/ordering/ui/adapter/cart/CartRecentlyAdapter.kt
- presentation/src/main/java/com/woowahan/ordering/ui/adapter/cart/RecentlyAdapter.kt
- presentation/src/main/java/com/woowahan/ordering/ui/fragment/cart/CartFragment.kt
- presentation/src/main/java/com/woowahan/ordering/ui/fragment/cart/recently/RecentlyViewedFragment.kt
- presentation/src/main/java/com/woowahan/ordering/ui/viewmodel/RecentlyViewedViewModel.kt
- presentation/src/main/res/layout/fragment_recently_viewed.xml
- presentation/src/main/res/layout/item_recently_viewed.xml
- 최근 본 상품 화면
- close #69 
- 최근 본 상품 조회화면을 구현했습니다.
- 해당 화면에서도 아이템이 장바구니에 담겼는지 여부를 알아야 해서 유스케이스를 수정했습니다.
- 고민했던 부분은 장바구니에 담는 바텀시트를 연결할 때 필요한 자료형이 Food인점..
- 상세 화면으로 이동
- 백스택 관리
> [FEAT] 최근 본 상품 화면 구현

- presentation/src/main/java/com/woowahan/ordering/ui/fragment/detail/DetailFragment.kt
- presentation/src/main/java/com/woowahan/ordering/ui/viewmodel/DetailViewModel.kt
- presentation/src/main/res/layout/item_detail_images.xml
- DetailFragment
- close #71
- 음식 자세히 보기 화면 수정
- 음식 주문 시 thumbnail을 thumbImage의 0번 index 보내기
- 다른 화면 이동 후 종료 시점에 어댑터 초기화하기(lazy 사용하지 않기)
- tabLayout Item Ripple 제거하기
> [FIX] #71 - 음식 자세히 보기 화면

- presentation/src/main/java/com/woowahan/ordering/ui/contracts/Contracts.kt
- presentation/src/main/java/com/woowahan/ordering/ui/viewmodel/CartViewModel.kt
Co-Authored-By: 주지혜 <oreocube13@gmail.com>
- close #73
- CartFragment
- 장바구니 화면 수정
> [FIX] #73 - 주문 예상 시간 contracts에 추가

- domain/src/main/java/com/woowahan/ordering/domain/usecase/food/GetMenuListUseCase.kt
- 메인화면
- close #84 
- 할인율이 오름차순으로 정렬되고 있던 오류 수정
> [FIX] #84 - 할인율 내림차순 정렬

- presentation/src/main/java/com/woowahan/ordering/ui/adapter/cart/CartRecentlyAdapter.kt
- presentation/src/main/java/com/woowahan/ordering/ui/adapter/cart/RecentlyAdapter.kt
- presentation/src/main/java/com/woowahan/ordering/ui/adapter/viewholder/ItemRecentlyViewHolder.kt
- presentation/src/main/java/com/woowahan/ordering/ui/fragment/cart/CartFragment.kt
- presentation/src/main/java/com/woowahan/ordering/ui/fragment/cart/recently/RecentlyViewedFragment.kt
- presentation/src/main/java/com/woowahan/ordering/ui/fragment/detail/DetailFragment.kt
- presentation/src/main/java/com/woowahan/ordering/ui/fragment/home/HomeFragment.kt
- presentation/src/main/java/com/woowahan/ordering/util/FragmentReplace.kt
- presentation/src/main/res/layout/fragment_recently_viewed.xml
- presentation/src/main/res/layout/item_cart_recently.xml
- presentation/src/main/res/layout/item_recently_grid.xml
- presentation/src/main/res/layout/item_recently_horizontal.xml
- CartFragment, RecentlyViewedFragment
- close #92
-  RecentlyAdapter 리팩토링 및 클릭 시 바텀 시트, 화면 이동 구현
- RecentlyAdapter ViewHolder Grid/Horizontal Sealed Class로 분리
- Recently 아이템 클릭 시 화면 이동
- 장바구니 버튼 클릭 시 바텀 시트 띄우기
> [REFECTOR] #92 - RecentlyAdapter 리팩토링 및 클릭 시 바텀 시트, 화면 이동 구현

- presentation/src/main/java/com/woowahan/ordering/ui/fragment/cart/recently/RecentlyViewedFragment.kt
- CartFragment, RecentlyViewedFragment
-  RecentlyAdapter 리팩토링 및 클릭 시 바텀 시트, 화면 이동 구현
- RecentlyAdapter ViewHolder Grid/Horizontal Sealed Class로 분리
- Recently 아이템 클릭 시 화면 이동
- 장바구니 버튼 클릭 시 바텀 시트 띄우기
> [REFECTOR] #92 - 아이템 클릭 이벤트 연결

- presentation/src/main/java/com/woowahan/ordering/ui/adapter/cart/CartRecentlyAdapter.kt
- presentation/src/main/java/com/woowahan/ordering/ui/adapter/viewholder/ItemFoodBestViewHolder.kt
- presentation/src/main/java/com/woowahan/ordering/ui/decorator/ItemSpacingDecoratorWithHeader.kt
- presentation/src/main/java/com/woowahan/ordering/ui/fragment/cart/recently/RecentlyViewedFragment.kt
- presentation/src/main/java/com/woowahan/ordering/ui/fragment/home/main/MainDishFragment.kt
- presentation/src/main/java/com/woowahan/ordering/ui/fragment/home/other/OtherDishFragment.kt
- presentation/src/main/java/com/woowahan/ordering/ui/fragment/order/OrderListFragment.kt
- presentation/src/main/java/com/woowahan/ordering/ui/fragment/order/detail/OrderDetailFragment.kt
- 리사이클러뷰 어댑터
- close #106
-  ItemDecorator 관련된 Grid Spacing이 잘못 설정되는 오류
- 관련된 Grid 리사이클러뷰 아이템들의 Spacing이 모두 조절됩니다.
> [FIX] #106 - ItemDecorator 관련된 Grid Spacing 오류

- presentation/src/main/java/com/woowahan/ordering/ui/fragment/detail/DetailFragment.kt
- presentation/src/main/java/com/woowahan/ordering/ui/fragment/home/best/BestFragment.kt
- presentation/src/main/java/com/woowahan/ordering/ui/fragment/home/main/MainDishFragment.kt
- presentation/src/main/java/com/woowahan/ordering/ui/fragment/home/other/OtherDishFragment.kt
- presentation/src/main/java/com/woowahan/ordering/util/ToastUtil.kt
- presentation/src/main/res/drawable/ic_bad.xml
- presentation/src/main/res/layout/fragment_best.xml
- presentation/src/main/res/layout/fragment_detail.xml
- presentation/src/main/res/layout/fragment_main_dish.xml
- presentation/src/main/res/layout/fragment_other_dish.xml
- presentation/src/main/res/layout/layout_no_internet.xml
- presentation/src/main/res/values/strings.xml
- 공통
- close #131
- 기본적인 로직은 아래와 같습니다. 
1. 기존에 작성해둔 네트워크 확장함수 사용하여 API 요청 전에 네트워크 연결을 확인
2. 연결이 있으면 데이터를 요청, 없으면 다른 화면 표출
- 네트워크 연결이 없을 때 표시할 레이아웃에는 '다시 시도' 버튼 존재
- '다시 시도' 버튼을 눌렀을 때도 마찬가지로 위의 1, 2 번을 차례로 수행
- 그때도 여전히 연결이 없는 경우, 화면이 변하지 않아 멈춘건가 싶은 느낌이 들 수도 있다고 판단 -> 토스트 메시지로 사용자에게 알림
<p align="center">
</p>
> [FEAT] 네트워크 연결이 없는 경우 대응

- presentation/src/main/java/com/woowahan/ordering/ui/fragment/cart/CartFragment.kt
- close #134 
- 여러 플로우 관찰 시 repeatOnLifecycle 내에서 여러 launch 블록 선언하도록 수정
> [REFACTOR] #134 - 여러 플로우 관찰 코드 수정

- presentation/src/main/java/com/woowahan/ordering/ui/adapter/DiffUtils.kt
- presentation/src/main/java/com/woowahan/ordering/ui/adapter/home/BestFoodAdapter.kt
- presentation/src/main/java/com/woowahan/ordering/ui/adapter/viewholder/ItemFoodBestViewHolder.kt
- 기획전
- close #143 
- 기획전 화면에도 payload 적용
- 외부 어댑터의 `onBindViewHolder(holder, positon, payloads)` 에서 화면을 다시 그리는 holder.bind() 가 아닌 submitList()로 내부 리사이클러뷰에 변경된 리스트만 전달하도록 하여 해결
> [FIX] #143 - 기획전 payload 적용

- presentation/src/main/java/com/woowahan/ordering/ui/fragment/home/HomeFragment.kt
- HomeFragment
- close #97
- 홈 화면 수정 사항
- Binding 변수를 nullable하도록 수정 및 onDestroyView 호출 시 null로 초기화
- 리스트 아이템 헤더부분 Space 수정
- 기획전 아이템 Space 없어지는 버그 수정
- onDestroy 시 필요없는 초기화 코드 제거
> [FIX] #97 - onDestroy 필요없는 코드 제거

- presentation/src/main/java/com/woowahan/ordering/ui/fragment/home/HomeFragment.kt
- presentation/src/main/java/com/woowahan/ordering/ui/fragment/home/best/BestFragment.kt
- presentation/src/main/java/com/woowahan/ordering/ui/fragment/home/main/MainDishFragment.kt
- presentation/src/main/java/com/woowahan/ordering/ui/fragment/home/other/OtherDishFragment.kt
- HomeFragment
- close #97
- 홈 화면 수정 사항
- Binding 변수를 nullable하도록 수정 및 onDestroyView 호출 시 null로 초기화
- 리스트 아이템 헤더부분 Space 수정
- 기획전 아이템 Space 없어지는 버그 수정
- 뷰페이저 onDestroy시 메모리 해제하기
> [FIX] #97 - 뷰페이저 onDestroy시 메모리 해제하기

- presentation/src/main/java/com/woowahan/ordering/ui/fragment/cart/CartFragment.kt
- presentation/src/main/java/com/woowahan/ordering/ui/fragment/detail/DetailFragment.kt
- presentation/src/main/java/com/woowahan/ordering/util/FragmentReplace.kt
- 프래그먼트 Replace 관련
- close #209 
- 장바구니에서 최근 본 상품을 선택했을 때 홈 화면으로 팅기는 버그
- 백 스택은 이미 백스택에 존재하더라도 쌓일 수 있도록 수정
- CartFragment는 하나만 생성되도록 popBackStack 활용
- DetailFragment는 계속 BackStack에 쌓일 수 있도록 수정
> [FIX] #209 - 장바구니에서 최근 본 상품을 선택했을 때 홈 화면으로 팅기는 버그

- presentation/src/main/java/com/woowahan/ordering/ui/fragment/detail/DetailFragment.kt
- presentation/src/main/java/com/woowahan/ordering/ui/fragment/home/best/BestFragment.kt
- presentation/src/main/java/com/woowahan/ordering/ui/fragment/home/main/MainDishFragment.kt
- presentation/src/main/java/com/woowahan/ordering/ui/fragment/home/other/OtherDishFragment.kt
- presentation/src/main/java/com/woowahan/ordering/util/SnackBarUtil.kt
- 공통
- close #219 
- 재시도 버튼을 여러번 누를 경우, 토스트 메시지가 화면에 장시간 남아있는 버그 수정
- 재시도 버튼 중복 클릭 방지
- 토스트는 정해진 시간동안 화면에 유지되고, 화면을 이동하거나 앱을 종료한 후에도 남아있을 수 있어 스낵바로 변경하여 해결
> [FIX] #219 - 네트워크 연결 메시지가 화면에 장시간 남아있는 버그 수정

- data/src/main/java/com/woowahan/ordering/data/entity/SimpleOrderEntity.kt
- data/src/main/java/com/woowahan/ordering/data/local/dao/OrderDao.kt
- data/src/main/java/com/woowahan/ordering/data/mapper/SimpleOrderMapper.kt
- domain/src/main/java/com/woowahan/ordering/domain/model/SimpleOrder.kt
- presentation/src/main/java/com/woowahan/ordering/ui/binding/TextViewBindingAdapter.kt
- presentation/src/main/java/com/woowahan/ordering/util/DateUtil.kt
- presentation/src/main/res/layout/item_order_simple.xml
- presentation/src/main/res/values/strings.xml
- 주문내역
- close #221 
- 배달 상태 변수 추가후 데이터바인딩
- 불필요한 바인딩 어댑터 제거
- 남은 시간이 0초여도 표시되는 버그 수정
> [FIX] #221 - 주문내역 배송 상태 업데이트 방법 추가

- presentation/src/main/java/com/woowahan/ordering/ui/adapter/home/CountAndFilterAdapter.kt
- presentation/src/main/java/com/woowahan/ordering/ui/fragment/home/other/OtherDishFragment.kt
- 뜨끈한 국물요리, 정갈한 밑반찬
- close #223 
- CountAndFilterAdapter 의 `notifyDataSetChanged()` 를 `notifyItemChanged(0)` 으로 변경하여 해결
> [FIX] #223 - 상세화면에서 뒤로 가면 리스트 반짝이는 버그 해결
