woowa-techcamp-2022/android-banchan-07

build.gradle, data/build.gradle, domain/build.gradle, presentation/build.gradle, presentation/src/main/AndroidManifest.xml, presentation/src/main/java/com/woowahan/ordering/application/HiltApplication.kt, presentation/src/main/java/com/woowahan/ordering/di/DataSourceModule.kt, presentation/src/main/java/com/woowahan/ordering/di/LocalModule.kt, presentation/src/main/java/com/woowahan/ordering/di/RemoteModule.kt, presentation/src/main/java/com/woowahan/ordering/di/RepositoryModule.kt
=> [CHORE] #4 - project library

data/src/main/java/com/woowahan/ordering/data/entity/CartEntity.kt, data/src/main/java/com/woowahan/ordering/data/entity/RecentlyEntity.kt, data/src/main/java/com/woowahan/ordering/data/entity/SimpleOrderEntity.kt, data/src/main/java/com/woowahan/ordering/data/mapper/CartMapper.kt, data/src/main/java/com/woowahan/ordering/data/mapper/RecentlyMapper.kt, data/src/main/java/com/woowahan/ordering/data/mapper/SimpleOrderMapper.kt, domain/src/main/java/com/woowahan/ordering/domain/model/Cart.kt, domain/src/main/java/com/woowahan/ordering/domain/model/Recently.kt, domain/src/main/java/com/woowahan/ordering/domain/model/SimpleOrder.kt
=> [REFECTOR] #8 - Variable Name 'Name' To 'Title'

data/src/main/java/com/woowahan/ordering/data/local/dao/OrderDao.kt
=> [FIX] #10 - 잘못된 쿼리 Field 수정

presentation/src/main/java/com/woowahan/ordering/ui/activity/MainActivity.kt, presentation/src/main/java/com/woowahan/ordering/ui/adapter/home/ViewPagerAdapter.kt, presentation/src/main/java/com/woowahan/ordering/ui/fragment/home/HomeFragment.kt, presentation/src/main/java/com/woowahan/ordering/ui/fragment/home/best/BestFragment.kt, presentation/src/main/java/com/woowahan/ordering/ui/fragment/home/main/MainDishFragment.kt, presentation/src/main/java/com/woowahan/ordering/ui/fragment/home/other/OtherDishFragment.kt, presentation/src/main/java/com/woowahan/ordering/ui/fragment/home/other/kind/OtherKind.kt, presentation/src/main/java/com/woowahan/ordering/ui/util/FragmentReplace.kt, presentation/src/main/res/layout/fragment_best.xml, presentation/src/main/res/layout/fragment_home.xml, presentation/src/main/res/layout/fragment_main_dish.xml, presentation/src/main/res/layout/fragment_other_dish.xml, presentation/src/main/res/values/array_tab.xml, presentation/src/main/res/values/strings.xml, presentation/src/main/res/values/themes.xml
- HomeFragment
- close #17
- HomeFragment Container 설정
- MainActivity에 HomeFragment Add
- ViewPager, TabLayout 추가 및 연동
- 화면 클릭 이벤트 Page Fragment마다 Callback Function 넣기
=> [FEAT] #17 - HomeFragment Container

presentation/build.gradle, presentation/src/main/AndroidManifest.xml, presentation/src/main/java/com/woowahan/ordering/ui/activity/MainActivity.kt, presentation/src/main/java/com/woowahan/ordering/ui/adapter/DiffUtils.kt, presentation/src/main/java/com/woowahan/ordering/ui/adapter/home/BestFoodAdapter.kt, presentation/src/main/java/com/woowahan/ordering/ui/adapter/home/FoodGridAdapter.kt, presentation/src/main/java/com/woowahan/ordering/ui/adapter/home/HeaderAdapter.kt, presentation/src/main/java/com/woowahan/ordering/ui/adapter/viewholder/ItemFoodBestViewHolder.kt, presentation/src/main/java/com/woowahan/ordering/ui/adapter/viewholder/ItemFoodViewHolder.kt, presentation/src/main/java/com/woowahan/ordering/ui/binding/ImageViewBindingAdapter.kt, presentation/src/main/java/com/woowahan/ordering/ui/binding/TextViewBindingAdapter.kt, presentation/src/main/java/com/woowahan/ordering/ui/decorator/ItemSpacingDecorator.kt, presentation/src/main/java/com/woowahan/ordering/ui/decorator/ItemSpacingDecoratorWithHeader.kt, presentation/src/main/java/com/woowahan/ordering/ui/dialog/CartBottomSheet.kt, presentation/src/main/java/com/woowahan/ordering/ui/fragment/home/best/BestFragment.kt, presentation/src/main/java/com/woowahan/ordering/ui/viewmodel/BestViewModel.kt, presentation/src/main/java/com/woowahan/ordering/util/SizeUtil.kt, presentation/src/main/res/drawable/bg_best_chip.xml, presentation/src/main/res/layout/fragment_best.xml, presentation/src/main/res/layout/item_food_best.xml, presentation/src/main/res/layout/item_food_grid.xml, presentation/src/main/res/layout/item_food_linear.xml, presentation/src/main/res/layout/item_header.xml, presentation/src/main/res/values/dimen_size.xml
- BestFragment
- close #23
- BestFragment 구현하기
- 리사이클러뷰 어댑터 구현
- Item Spacing 넣기
- 서버에서 데이터 불러오기
=> [FEAT] #23 - BestFragment

data/src/main/java/com/woowahan/ordering/data/mapper/FoodMapper.kt, domain/src/main/java/com/woowahan/ordering/domain/model/SortType.kt, domain/src/main/java/com/woowahan/ordering/domain/usecase/food/GetMenuListUseCase.kt, presentation/build.gradle, presentation/src/main/java/com/woowahan/ordering/ui/adapter/home/CountAndFilterAdapter.kt, presentation/src/main/java/com/woowahan/ordering/ui/adapter/home/FilterAdapter.kt, presentation/src/main/java/com/woowahan/ordering/ui/adapter/home/HeaderAdapter.kt, presentation/src/main/java/com/woowahan/ordering/ui/decorator/ItemSpacingDecoratorWithHeader.kt, presentation/src/main/java/com/woowahan/ordering/ui/fragment/home/other/OtherDishFragment.kt, presentation/src/main/java/com/woowahan/ordering/ui/viewmodel/OtherDishViewModel.kt, presentation/src/main/res/drawable/bg_spinner.xml, presentation/src/main/res/layout/fragment_other_dish.xml, presentation/src/main/res/layout/item_count_and_filter.xml, presentation/src/main/res/layout/spinner_filter_dropdown.xml, presentation/src/main/res/layout/spinner_filter_top.xml, presentation/src/main/res/values/array_spinner.xml, presentation/src/main/res/values/dimen_size.xml, presentation/src/main/res/values/strings.xml
- 국, 반찬 화면
- close #25 
- OtherDishFragment 구현
=> [FEAT] OtherDishFragment

presentation/src/main/res/layout/item_food_grid.xml, presentation/src/main/res/layout/item_food_linear.xml
- 공통
- close #31 
- 할인하지 않는 경우 할인율, 정가 숨김
=> [FIX] 할인하지 않는 경우 할인율, 정가 숨김

presentation/src/main/java/com/woowahan/ordering/ui/fragment/home/HomeFragment.kt, presentation/src/main/java/com/woowahan/ordering/ui/fragment/home/best/BestFragment.kt, presentation/src/main/java/com/woowahan/ordering/ui/fragment/home/main/MainDishFragment.kt, presentation/src/main/java/com/woowahan/ordering/ui/fragment/home/other/OtherDishFragment.kt, presentation/src/main/java/com/woowahan/ordering/ui/util/FragmentReplace.kt, presentation/src/main/java/com/woowahan/ordering/ui/widget/OrientationAwareRecyclerView.kt, presentation/src/main/res/layout/fragment_best.xml
- HomeFragment
- close #35
- HomeFragment 버그 수정
- 화면 회전 시 앱 죽는 버그
- 기획전 화면 리사이클러뷰 Horizontal 스크롤 안되는 버그
=> [FIX] #35 - HomeFragment

presentation/src/main/java/com/woowahan/ordering/ui/fragment/home/main/MainDishFragment.kt
- screen type
- close #39
- by lazy를 통한 초기화 시 타 화면 이동 후 다시 로드했을 때 상태가 남아있던 리사이클러뷰가 망가지는 오류
##Task
- by lazy를 lateinit으로 수정
=> [FIX] #39 - 어댑터 초기화 시 lateinit 사용

presentation/src/main/java/com/woowahan/ordering/ui/dialog/CartBottomSheet.kt
- close #47
- UiState의 Import가 잘못되어 있는 버그 수정
=> [FIX] #47 - UiState Import 오류

data/build.gradle, data/src/main/java/com/woowahan/ordering/data/datasource/CartDataSource.kt, data/src/main/java/com/woowahan/ordering/data/local/dao/CartDao.kt, data/src/main/java/com/woowahan/ordering/data/local/datasource/CartDataSourceImpl.kt, data/src/main/java/com/woowahan/ordering/data/repository/CartRepositoryImpl.kt, domain/src/main/java/com/woowahan/ordering/domain/repository/CartRepository.kt, domain/src/main/java/com/woowahan/ordering/domain/usecase/cart/GetCartUseCase.kt, domain/src/main/java/com/woowahan/ordering/domain/usecase/food/GetBestListUseCase.kt, domain/src/main/java/com/woowahan/ordering/domain/usecase/food/GetMenuListUseCase.kt, presentation/src/main/java/com/woowahan/ordering/ui/activity/MainActivity.kt, presentation/src/main/java/com/woowahan/ordering/ui/viewmodel/MainViewModel.kt, presentation/src/main/res/layout/action_cart.xml
- close #15
- MainActivity
- 메인액티비티의 컨테이너로 들어가는 기본 뷰 설정
- Cart 갯수 변경 시 툴바에 반영
=> [FEAT] #15 - MainActivity

data/src/main/java/com/woowahan/ordering/data/mapper/RecentlyMapper.kt, domain/src/main/java/com/woowahan/ordering/domain/model/Recently.kt, presentation/src/main/java/com/woowahan/ordering/ui/binding/TextViewBindingAdapter.kt, presentation/src/main/java/com/woowahan/ordering/ui/binding/ViewBindingAdapter.kt, presentation/src/main/java/com/woowahan/ordering/util/DateUtil.kt, presentation/src/main/res/layout/item_cart.xml, presentation/src/main/res/layout/item_cart_header.xml, presentation/src/main/res/layout/item_cart_recently.xml, presentation/src/main/res/layout/item_recently_viewed.xml, presentation/src/main/res/layout/item_total_price.xml, presentation/src/main/res/values/dimen_size.xml, presentation/src/main/res/values/strings.xml
- 장바구니
- close #42 
- 장바구니 화면 구현에 필요한 레이아웃 구현
- 최근 본 아이템 시각을 스트링으로 변환하는 유틸 함수 및 바인딩 어댑터 작성
=> [UI] 장바구니 화면 레이아웃

data/src/main/java/com/woowahan/ordering/data/local/dao/RecentlyDao.kt, presentation/src/main/java/com/woowahan/ordering/ui/fragment/detail/DetailFragment.kt, presentation/src/main/java/com/woowahan/ordering/ui/viewmodel/DetailViewModel.kt, presentation/src/main/res/layout/item_detail_info.xml
- close #37
- 음식 자세히 보기 화면
- 음식 자세히 보기 화면 구현하기
- Detail 들어갈 때 Recently에 값 넣기
- 돈 계산하기
=> [FEAT] #37 - DetailFragment

data/src/main/java/com/woowahan/ordering/data/datasource/CartDataSource.kt, data/src/main/java/com/woowahan/ordering/data/datasource/OrderDataSource.kt, data/src/main/java/com/woowahan/ordering/data/local/dao/CartDao.kt, data/src/main/java/com/woowahan/ordering/data/local/dao/OrderDao.kt, data/src/main/java/com/woowahan/ordering/data/local/datasource/CartDataSourceImpl.kt, data/src/main/java/com/woowahan/ordering/data/local/datasource/OrderDataSourceImpl.kt, data/src/main/java/com/woowahan/ordering/data/repository/CartRepositoryImpl.kt, data/src/main/java/com/woowahan/ordering/data/repository/OrderRepositoryImpl.kt, domain/src/main/java/com/woowahan/ordering/domain/model/CartListItem.kt, domain/src/main/java/com/woowahan/ordering/domain/repository/CartRepository.kt, domain/src/main/java/com/woowahan/ordering/domain/repository/OrderRepository.kt, domain/src/main/java/com/woowahan/ordering/domain/usecase/cart/SelectAllCartUseCase.kt, domain/src/main/java/com/woowahan/ordering/domain/usecase/order/InsertOrderUseCase.kt, presentation/src/main/java/com/woowahan/ordering/di/usecase/CartUseCaseModule.kt, presentation/src/main/java/com/woowahan/ordering/di/usecase/OrderUseCaseModule.kt, presentation/src/main/java/com/woowahan/ordering/ui/adapter/cart/CartAdapter.kt, presentation/src/main/java/com/woowahan/ordering/ui/viewmodel/CartViewModel.kt, presentation/src/main/res/layout/item_cart_header.xml, presentation/src/main/res/values/strings.xml
- 장바구니
- close #55 
- 장바구니에 담긴 아이템의 클릭 이벤트를 처리합니다.
- 수량 변경 기능
- 전체 선택, 전세 선택 해제 기능
- 상품 삭제 기능
- 선택된 상품 주문 기능
=> [FEAT] 장바구니 담긴 상품 상태 변경 기능 구현

presentation/src/main/java/com/woowahan/ordering/ui/activity/MainActivity.kt, presentation/src/main/java/com/woowahan/ordering/ui/fragment/detail/DetailFragment.kt, presentation/src/main/java/com/woowahan/ordering/ui/fragment/home/HomeFragment.kt, presentation/src/main/java/com/woowahan/ordering/ui/fragment/home/best/BestFragment.kt, presentation/src/main/java/com/woowahan/ordering/ui/fragment/home/main/MainDishFragment.kt, presentation/src/main/java/com/woowahan/ordering/ui/fragment/home/other/OtherDishFragment.kt, presentation/src/main/res/layout/item_cart_recently.xml
- close #61
- CartFragment
- 장바구니 화면 수정 사항
- 최근 본 상품 리스트 Space 수정
- 백 버튼 클릭 시 뒤 페이지로 이동하기
- 프래그먼트별 툴바 변경
- 장바구니 추가 시 장바구니 화면 이동 버튼 클릭하면 이동하기
=> [FIX] #61 - CartFragment

presentation/src/main/res/drawable/bg_large_rounded_button.xml, presentation/src/main/res/drawable/bg_medium_rounded_button.xml, presentation/src/main/res/drawable/bg_small_rounded_button.xml, presentation/src/main/res/layout/bottom_sheet_cart.xml, presentation/src/main/res/layout/item_cart.xml, presentation/src/main/res/layout/item_detail_info.xml, presentation/src/main/res/layout/item_food_grid.xml, presentation/src/main/res/layout/item_food_horizontal.xml, presentation/src/main/res/layout/item_food_vertical.xml, presentation/src/main/res/layout/item_recently_viewed.xml, presentation/src/main/res/values/dimen_size.xml, presentation/src/main/res/values/style_rounded_button.xml
- close #63 
- 버튼 동그라미 모양 적용
- Drawable, 스타일 추가
- 동그라미 버튼에 적용하기
=> [FIX] #63 - 버튼 Drawable 추가 및 적용

data/src/main/java/com/woowahan/ordering/data/datasource/CartDataSource.kt, data/src/main/java/com/woowahan/ordering/data/local/dao/CartDao.kt, data/src/main/java/com/woowahan/ordering/data/local/datasource/CartDataSourceImpl.kt, data/src/main/java/com/woowahan/ordering/data/repository/CartRepositoryImpl.kt, domain/src/main/java/com/woowahan/ordering/domain/repository/CartRepository.kt, domain/src/main/java/com/woowahan/ordering/domain/usecase/cart/DeleteAllSelectedCartUseCase.kt, presentation/src/main/java/com/woowahan/ordering/di/usecase/CartUseCaseModule.kt, presentation/src/main/java/com/woowahan/ordering/ui/adapter/cart/CartAdapter.kt, presentation/src/main/java/com/woowahan/ordering/ui/fragment/cart/CartFragment.kt, presentation/src/main/java/com/woowahan/ordering/ui/viewmodel/CartViewModel.kt
- 장바구니
- close #64 
- 장바구니에 있는 상품 중 선택된 상품을 삭제하는 기능 구현
=> [FEAT] 장바구니 선택된 상품 삭제 기능 구현

data/src/main/java/com/woowahan/ordering/data/datasource/OrderDataSource.kt, data/src/main/java/com/woowahan/ordering/data/local/dao/OrderDao.kt, data/src/main/java/com/woowahan/ordering/data/local/datasource/OrderDataSourceImpl.kt, data/src/main/java/com/woowahan/ordering/data/repository/OrderRepositoryImpl.kt, domain/src/main/java/com/woowahan/ordering/domain/repository/OrderRepository.kt, domain/src/main/java/com/woowahan/ordering/domain/usecase/order/GetOrderedCartByDeliveryTimeUseCase.kt, domain/src/main/java/com/woowahan/ordering/domain/usecase/order/GetSimpleOrderUseCase.kt, presentation/src/main/java/com/woowahan/ordering/ui/activity/MainActivity.kt, presentation/src/main/java/com/woowahan/ordering/ui/adapter/DiffUtils.kt, presentation/src/main/java/com/woowahan/ordering/ui/adapter/order/SimpleOrderListAdapter.kt, presentation/src/main/java/com/woowahan/ordering/ui/binding/TextViewBindingAdapter.kt, presentation/src/main/java/com/woowahan/ordering/ui/fragment/order/OrderListFragment.kt, presentation/src/main/java/com/woowahan/ordering/ui/viewmodel/OrderListViewModel.kt, presentation/src/main/res/layout/fragment_order_list.xml, presentation/src/main/res/layout/item_order_simple.xml, presentation/src/main/res/values/dimen_size.xml, presentation/src/main/res/values/strings.xml
- close #67
- OrderListFragment
- 주문내역 리스트 화면
- 주문내역 리스트 어댑터 만들기
- 툴바 설정하기
=> [FEAT] #67 - 주문내역 리스트 화면

contracts/src/main/java/com/woowahan/ordering/contracts/DateUtil.kt, data/src/main/java/com/woowahan/ordering/data/datasource/OrderDataSource.kt, data/src/main/java/com/woowahan/ordering/data/local/datasource/OrderDataSourceImpl.kt, data/src/main/java/com/woowahan/ordering/data/mapper/OrderListMapper.kt, data/src/main/java/com/woowahan/ordering/data/repository/OrderRepositoryImpl.kt, domain/src/main/java/com/woowahan/ordering/domain/model/OrderedCartList.kt, domain/src/main/java/com/woowahan/ordering/domain/repository/OrderRepository.kt, presentation/src/main/java/com/woowahan/ordering/ui/adapter/DiffUtils.kt, presentation/src/main/java/com/woowahan/ordering/ui/adapter/order/OrderDetailFooterAdapter.kt, presentation/src/main/java/com/woowahan/ordering/ui/adapter/order/OrderDetailHeaderAdapter.kt, presentation/src/main/java/com/woowahan/ordering/ui/adapter/order/OrderDetailListAdapter.kt, presentation/src/main/java/com/woowahan/ordering/ui/adapter/order/SimpleOrderListAdapter.kt, presentation/src/main/java/com/woowahan/ordering/ui/binding/TextViewBindingAdapter.kt, presentation/src/main/java/com/woowahan/ordering/ui/fragment/order/OrderListFragment.kt, presentation/src/main/java/com/woowahan/ordering/ui/fragment/order/detail/OrderDetailFragment.kt, presentation/src/main/java/com/woowahan/ordering/ui/viewmodel/OrderDetailViewModel.kt, presentation/src/main/res/layout/fragment_order_detail.xml, presentation/src/main/res/layout/item_order_detail_footer.xml, presentation/src/main/res/layout/item_order_detail_header.xml, presentation/src/main/res/layout/item_order_detail_list.xml, presentation/src/main/res/values/dimen_size.xml, presentation/src/main/res/values/strings.xml
- 주문상세
- close #75 
- 주문 상세 화면 구현
- 페어프로그래밍으로 진행
=> [FEAT] 주문 상세 화면 구현

data/src/main/java/com/woowahan/ordering/data/datasource/CartDataSource.kt, data/src/main/java/com/woowahan/ordering/data/local/datasource/CartDataSourceImpl.kt, data/src/main/java/com/woowahan/ordering/data/mapper/CartMapper.kt, data/src/main/java/com/woowahan/ordering/data/repository/CartRepositoryImpl.kt, domain/src/main/java/com/woowahan/ordering/domain/model/CartResult.kt, domain/src/main/java/com/woowahan/ordering/domain/repository/CartRepository.kt, domain/src/main/java/com/woowahan/ordering/domain/usecase/cart/GetCartResultUseCase.kt, presentation/src/main/java/com/woowahan/ordering/di/usecase/CartUseCaseModule.kt, presentation/src/main/java/com/woowahan/ordering/ui/adapter/DiffUtils.kt, presentation/src/main/java/com/woowahan/ordering/ui/adapter/cart/CartAdapter.kt, presentation/src/main/java/com/woowahan/ordering/ui/fragment/cart/CartFragment.kt, presentation/src/main/java/com/woowahan/ordering/ui/fragment/cart/CartListItem.kt, presentation/src/main/java/com/woowahan/ordering/ui/viewmodel/CartViewModel.kt
- 장바구니
- close #79 
- 장바구니 화면 로직을 개선
- 계산 로직 데이터 레이어로 이동
=> [REFACTOR] 장바구니 로직 코드 개선

presentation/src/main/java/com/woowahan/ordering/ui/dialog/CartDialogFragment.kt, presentation/src/main/java/com/woowahan/ordering/ui/dialog/IsExistsCartDialogFragment.kt
- 공통
- close #85 
- dismiss() 호출 누락으로 다이얼로그가 사라지지 않던 버그 수정
=> [FIX] #85 - 다이얼로그가 사라지지 않는 버그 수정

domain/src/main/java/com/woowahan/ordering/domain/usecase/food/GetMenuListUseCase.kt
=> [FIX] #84 #85 - UI 버그 수정

contracts/src/main/java/com/woowahan/ordering/contracts/Contracts.kt, contracts/src/main/java/com/woowahan/ordering/contracts/DateUtil.kt, data/src/main/java/com/woowahan/ordering/data/datasource/OrderDataSource.kt, data/src/main/java/com/woowahan/ordering/data/local/dao/OrderDao.kt, data/src/main/java/com/woowahan/ordering/data/local/datasource/OrderDataSourceImpl.kt, data/src/main/java/com/woowahan/ordering/data/repository/OrderRepositoryImpl.kt, domain/src/main/java/com/woowahan/ordering/domain/repository/OrderRepository.kt, domain/src/main/java/com/woowahan/ordering/domain/usecase/order/GetOrderedCartByDeliveryTimeUseCase.kt, presentation/src/main/java/com/woowahan/ordering/ui/activity/MainActivity.kt, presentation/src/main/java/com/woowahan/ordering/ui/adapter/order/OrderDetailHeaderAdapter.kt, presentation/src/main/java/com/woowahan/ordering/ui/binding/TextViewBindingAdapter.kt, presentation/src/main/java/com/woowahan/ordering/ui/fragment/order/detail/OrderDetailFragment.kt, presentation/src/main/java/com/woowahan/ordering/ui/viewmodel/OrderDetailViewModel.kt, presentation/src/main/res/layout/activity_main.xml, presentation/src/main/res/layout/fragment_order_detail.xml, presentation/src/main/res/layout/item_order_detail_header.xml, presentation/src/main/res/menu/menu_toolbar_order.xml
- 주문 상세
- close #91 
- 주문 상세화면으로 툴바 이동
- 새로고침을 위해 StateFlow를 SharedFlow로 변경 (with. 윤재님)
- 기타 상세 화면 텍스트 버그 수정
=> [FEAT] #91 - 주문 상세 화면 새로고침 구현 및 버그 수정

presentation/src/main/java/com/woowahan/ordering/ui/fragment/home/HomeFragment.kt
- HomeFragment
- close #97
- 홈 화면 수정 사항
- Binding 변수를 nullable하도록 수정 및 onDestroyView 호출 시 null로 초기화
=> [FIX] #97 - binding nullable

presentation/src/main/java/com/woowahan/ordering/ui/adapter/detail/DetailThumbImagesAdapter.kt
- HomeFragment
- close#99
- 홈 화면 수정 사항
=> [FIX] #99 - 자세히 보기 화면 썸네일 가져올 때 clear하기

presentation/src/main/java/com/woowahan/ordering/ui/activity/MainActivity.kt, presentation/src/main/java/com/woowahan/ordering/ui/fragment/cart/CartFragment.kt, presentation/src/main/java/com/woowahan/ordering/ui/fragment/cart/recently/RecentlyViewedFragment.kt, presentation/src/main/java/com/woowahan/ordering/ui/fragment/detail/DetailFragment.kt, presentation/src/main/java/com/woowahan/ordering/ui/fragment/home/HomeFragment.kt, presentation/src/main/java/com/woowahan/ordering/ui/fragment/order/OrderListFragment.kt, presentation/src/main/java/com/woowahan/ordering/ui/fragment/order/detail/OrderDetailFragment.kt
- 모든 프래그먼트
- close #102
- 프래그먼트의 companion object에 tag를 추가하고 화면 이동 시 태그 사용하기
=> [REFECTOR] #102 - 프래그먼트 TAG 추가

presentation/src/main/java/com/woowahan/ordering/ui/adapter/cart/CartAdapter.kt, presentation/src/main/java/com/woowahan/ordering/ui/fragment/cart/CartFragment.kt, presentation/src/main/java/com/woowahan/ordering/ui/fragment/cart/CartListItem.kt, presentation/src/main/java/com/woowahan/ordering/ui/uistate/CartUiState.kt, presentation/src/main/java/com/woowahan/ordering/ui/viewmodel/CartViewModel.kt, presentation/src/main/res/layout/item_empty.xml, presentation/src/main/res/values/strings.xml
- 장바구니
- close #94 
- close #96
=> [FEAT] #94 #96 - 장바구니 비었을 때 대응 및 성공 시 화면 전환

presentation/src/main/java/com/woowahan/ordering/ui/fragment/detail/DetailFragment.kt
- DetailFragment
- close #99
- 자세히 보기 화면에서 Cart 화면 이동 시 팅기는 버그
- 화면이 제거되어 팅기는 버그 수정
=> [FIX] #99 - 화면이 제거되어 팅기는 버그

presentation/src/main/res/layout/item_count_and_filter.xml, presentation/src/main/res/layout/item_food_best.xml, presentation/src/main/res/layout/item_type_and_filter.xml
- HomeFragment
- close #97
- 홈 화면 수정 사항
=> [FIX] #97 - 리스트 아이템 헤더부분 Space 수정

presentation/src/main/res/layout/item_cart_recently.xml
- 장바구니
- close #109 
- 커스텀 ItemDecoration 수정으로 인한 마진 수정
=> [FIX] #109 - 하단 최근 본 상품 마진 수정

presentation/src/main/res/layout/fragment_order_detail.xml
- OrderDetailFragment
- close #111
- 주문 상세보기 페이지 Background Color 수정
- Background Color 수정
=> [FIX] #111 - Background 색상이 잘려서 표시되는 버그 수정

presentation/src/main/java/com/woowahan/ordering/ui/adapter/viewholder/ItemFoodBestViewHolder.kt
=> [FIX] #97 - 기획전 아이템 Space 없어지는 버그 수정

presentation/src/main/java/com/woowahan/ordering/ui/adapter/cart/CartRecentlyAdapter.kt
- 장바구니
- close #109 
- 커스텀 ItemDecoration 수정으로 인한 장바구니 하단 최근 본 상품 마진 수정
- 장바구니 화면 하단 최근 본 상품 Spece 사라지는 버그 수정
=> [FIX] #109 - 장바구니 화면 하단 최근 본 상품 Spece 사라지는 버그 수정

presentation/src/main/java/com/woowahan/ordering/util/FragmentReplace.kt, presentation/src/main/res/layout/fragment_recently_viewed.xml
- RecentlyViewedFragment
- close #115
- 최근 본 상품 화면 수정 사항
- Fragment Added 버그 수정
- Top Space 제거하기
=> [FIX] #115 - RecentlyViewedFragment

presentation/src/main/java/com/woowahan/ordering/application/HiltApplication.kt, presentation/src/main/java/com/woowahan/ordering/ui/receiver/CartReceiver.kt, presentation/src/main/java/com/woowahan/ordering/util/NotificationUtil.kt, presentation/src/main/res/values/strings.xml
- Notification
- close #120
- Notification 리팩토링
- Application에서 Notification Channel 생성하는 코드 제거
- Notification Id, Notification Name을 strings.xml에서 관리
=> [REFECTOR] #120 - Notification 리팩토링

presentation/src/main/java/com/woowahan/ordering/ui/fragment/home/best/BestFragment.kt, presentation/src/main/java/com/woowahan/ordering/ui/fragment/home/main/MainDishFragment.kt, presentation/src/main/java/com/woowahan/ordering/ui/fragment/home/other/OtherDishFragment.kt, presentation/src/main/res/values/strings.xml
- 메인
- close #126 
- 메인 탭 4개의 헤더 텍스트 스트링 리소스로 관리
=> [CHORE] #126 - 하드코딩된 스트링 제거

data/src/main/java/com/woowahan/ordering/data/datasource/OrderDataSource.kt, data/src/main/java/com/woowahan/ordering/data/entity/OrderEntity.kt, data/src/main/java/com/woowahan/ordering/data/local/dao/OrderDao.kt, data/src/main/java/com/woowahan/ordering/data/local/datasource/OrderDataSourceImpl.kt, data/src/main/java/com/woowahan/ordering/data/mapper/OrderMapper.kt, data/src/main/java/com/woowahan/ordering/data/repository/OrderRepositoryImpl.kt, domain/src/main/java/com/woowahan/ordering/domain/model/Order.kt, domain/src/main/java/com/woowahan/ordering/domain/repository/OrderRepository.kt, domain/src/main/java/com/woowahan/ordering/domain/usecase/order/IsExistNotDeliveredOrderUseCase.kt, domain/src/main/java/com/woowahan/ordering/domain/usecase/order/UpdateOrderUseCase.kt, presentation/build.gradle, presentation/src/androidTest/java/com/woowahan/ordering/OrderDaoTest.kt, presentation/src/main/AndroidManifest.xml, presentation/src/main/java/com/woowahan/ordering/application/HiltApplication.kt, presentation/src/main/java/com/woowahan/ordering/di/usecase/OrderUseCaseModule.kt, presentation/src/main/java/com/woowahan/ordering/ui/activity/MainActivity.kt, presentation/src/main/java/com/woowahan/ordering/ui/receiver/CartReceiver.kt, presentation/src/main/java/com/woowahan/ordering/ui/viewmodel/CartViewModel.kt, presentation/src/main/java/com/woowahan/ordering/ui/viewmodel/MainViewModel.kt, presentation/src/main/java/com/woowahan/ordering/ui/worker/DeliveryTimeWorker.kt, presentation/src/main/res/layout/action_order.xml
- MainActivity
- close #117
- MainActivity Toolbar의 Order Badge WorkManager 사용해서 완료/미완료 표시하기
- Order 테이블에 isDelivered 필드 추가하기
- 주문된 아이템이 존재하는지를 리턴하는 IsExistNotDeliveredOrder UseCase 추가
- 아이템 배달 상태를 변경하는 UpdateIsDelivered 메서드 추가
- WorkManager를 사용해서 배달 상태 변경
=> [FIX] #117 - MainActivity Toolbar의 Order Badge 표시

presentation/src/main/java/com/woowahan/ordering/ui/adapter/DiffUtils.kt, presentation/src/main/java/com/woowahan/ordering/ui/adapter/cart/CartAdapter.kt, presentation/src/main/java/com/woowahan/ordering/ui/fragment/cart/CartFragment.kt, presentation/src/main/java/com/woowahan/ordering/ui/fragment/detail/DetailFragment.kt, presentation/src/main/java/com/woowahan/ordering/ui/fragment/home/best/BestFragment.kt, presentation/src/main/java/com/woowahan/ordering/ui/fragment/home/main/MainDishFragment.kt, presentation/src/main/java/com/woowahan/ordering/ui/fragment/home/other/OtherDishFragment.kt, presentation/src/main/java/com/woowahan/ordering/util/ToastUtil.kt, presentation/src/main/res/drawable/ic_bad.xml, presentation/src/main/res/layout/fragment_best.xml, presentation/src/main/res/layout/fragment_detail.xml, presentation/src/main/res/layout/fragment_main_dish.xml, presentation/src/main/res/layout/fragment_other_dish.xml, presentation/src/main/res/layout/item_total_price.xml, presentation/src/main/res/layout/layout_no_internet.xml, presentation/src/main/res/values/strings.xml
- 장바구니
- close #129 
- diffUtil 에서 `areItemsTheSame`, `areContentsTheSame` 반대로 사용하고 있던 오류 수정
- payloads 를 사용하여 `areItemsTheSame` 이 `true` 이고, `areContentsTheSame` 이 `false` 인 아이템만 새로 그리도록 수정
=> [FIX] #129 - 장바구니 어댑터 개선

data/src/main/java/com/woowahan/ordering/data/remote/base/BaseRemote.kt
- close #136
- Networking 오류 처리
- try catch문에서 처리 방식 변경하기
=> [FIX] #136 - Networking 오류 처리

presentation/src/main/java/com/woowahan/ordering/ui/viewmodel/BestViewModel.kt, presentation/src/main/java/com/woowahan/ordering/ui/viewmodel/MainDishViewModel.kt, presentation/src/main/java/com/woowahan/ordering/ui/viewmodel/OtherDishViewModel.kt
- 홈 화면
- close #138
- 장바구니 아이템 추가 시 정렬방식 초기화되는 버그
- ViewModel Job Cancel 코드 추가
=> [FIX] #138 - 장바구니 아이템 추가 시 반찬 리스트 정렬방식 초기화되는 버그

presentation/src/main/java/com/woowahan/ordering/ui/adapter/DiffUtils.kt
- 기획전을 제외한 메인 탭 3개
- close #141 
- foodDiffUtil 을 수정하여 장바구니 추가 시에 번쩍거리던 현상을 제거했습니다.
- 기획전 화면은 조금 더 들여다봐야 할 것 같습니다..
=> [FIX] #141 - 상품 리스트 payload 적용

presentation/src/main/java/com/woowahan/ordering/ui/adapter/DiffUtils.kt, presentation/src/main/java/com/woowahan/ordering/ui/adapter/home/BestFoodAdapter.kt, presentation/src/main/java/com/woowahan/ordering/ui/adapter/home/CountAndFilterAdapter.kt, presentation/src/main/java/com/woowahan/ordering/ui/adapter/home/FoodAdapter.kt, presentation/src/main/java/com/woowahan/ordering/ui/adapter/viewholder/ItemFoodBestViewHolder.kt, presentation/src/main/java/com/woowahan/ordering/ui/adapter/viewholder/ItemFoodViewHolder.kt, presentation/src/main/java/com/woowahan/ordering/ui/fragment/home/best/BestFragment.kt, presentation/src/main/java/com/woowahan/ordering/ui/fragment/home/main/MainDishFragment.kt, presentation/src/main/java/com/woowahan/ordering/ui/fragment/home/other/OtherDishFragment.kt
- 공통
- close #133 
- 어댑터 클릭 리스너 생성자 주입 방식으로 변경
=> [REFACTOR] #133 - 어댑터 클릭 리스너 생성자 주입 방식으로 변경

data/src/main/java/com/woowahan/ordering/data/remote/base/BaseRemote.kt, domain/src/main/java/com/woowahan/ordering/domain/usecase/food/GetBestListUseCase.kt, domain/src/main/java/com/woowahan/ordering/domain/usecase/food/GetMenuListUseCase.kt, presentation/build.gradle, presentation/src/main/java/com/woowahan/ordering/di/RemoteModule.kt, presentation/src/main/java/com/woowahan/ordering/network/ConnectionInterceptor.kt, presentation/src/main/java/com/woowahan/ordering/ui/fragment/home/best/BestFragment.kt, presentation/src/main/java/com/woowahan/ordering/ui/fragment/home/main/MainDishFragment.kt, presentation/src/main/java/com/woowahan/ordering/ui/fragment/home/other/OtherDishFragment.kt, presentation/src/main/java/com/woowahan/ordering/ui/uistate/ListUiState.kt, presentation/src/main/java/com/woowahan/ordering/ui/viewmodel/BestViewModel.kt, presentation/src/main/java/com/woowahan/ordering/ui/viewmodel/MainDishViewModel.kt, presentation/src/main/java/com/woowahan/ordering/ui/viewmodel/OtherDishViewModel.kt, presentation/src/main/java/com/woowahan/ordering/util/NetworkUtil.kt, presentation/src/main/res/layout/fragment_best.xml, presentation/src/main/res/layout/fragment_main_dish.xml, presentation/src/main/res/layout/fragment_other_dish.xml
- 공통
- close #131
- 네트워크 연결이 없는 경우를 대응
- 메인 탭 4개와 상세화면의 리모트 데이터 요청 전에 네트워크 연결 상태를 체크
- 네트워크 연결이 없는 경우 표시할 레이아웃 구성
- 데이터 요청 전 네트워크 연결 상태 체크
- 연결 상태에 따른 분기처리
- 다시 시도 버튼을 통해 리모트 데이터 재요청 시도
- 앱 실행 시 네트워크 체킹 및 오프라인일 때 재시도 다이얼로그
- Pull to Refresh 시 오프라인 레이아웃 표시
=> [FEAT] #131 - 네트워크 연결이 없는 경우 대응

presentation/src/main/AndroidManifest.xml, presentation/src/main/java/com/woowahan/ordering/ui/activity/MainActivity.kt
- MainActivity
- close #149
- 화면 회전 시 이벤트 받기
- Manifest activity의 configChanges 태그에 orientation과 screenSize를 지정
- Activity에서 onConfigurationChanged로 이벤트 핸들링
=> [FIX] #149 - 화면 회전 시 이벤트 받기 

presentation/src/main/java/com/woowahan/ordering/ui/adapter/viewholder/ItemFoodViewHolder.kt, presentation/src/main/java/com/woowahan/ordering/ui/adapter/viewholder/ItemRecentlyViewHolder.kt, presentation/src/main/java/com/woowahan/ordering/ui/binding/ViewBindingAdapter.kt, presentation/src/main/java/com/woowahan/ordering/ui/listener/OnThrottleClickListener.kt, presentation/src/main/res/layout/item_detail_info.xml
- 공통
- close #153
- 클릭이 여러번 되지 말아야 할 버튼에 커스텀 리스너를 만들어서 적용
- Throttle Button 클릭 리스너 만들기
- 필요한 버튼에 적용하기
=> [FIX] #153 - 버튼 클릭이 중복되지 않도록 수정

domain/src/main/java/com/woowahan/ordering/domain/usecase/food/GetMenuListUseCase.kt, presentation/src/main/java/com/woowahan/ordering/ui/adapter/home/TypeAndFilterAdapter.kt, presentation/src/main/java/com/woowahan/ordering/ui/fragment/home/main/MainDishFragment.kt, presentation/src/main/res/values/strings.xml
- 메인요리
- close #156 
- 메인요리 정렬 방식 변경 처리
- 기타 UI 버그 수정
=> [FIX] #156 - 메인요리 정렬 방식 변경 누락

presentation/src/main/java/com/woowahan/ordering/ui/dialog/CartBottomSheet.kt, presentation/src/main/res/drawable/bg_rounded_bottom_sheet.xml, presentation/src/main/res/layout/bottom_sheet_cart.xml, presentation/src/main/res/values/style_bottom_sheet.xml
=> [FIX] #159 - 장바구니 바텀시트 화면회전 대응

presentation/src/main/java/com/woowahan/ordering/ui/fragment/cart/CartFragment.kt, presentation/src/main/java/com/woowahan/ordering/ui/uistate/CartUiState.kt, presentation/src/main/java/com/woowahan/ordering/ui/viewmodel/CartBottomSheetViewModel.kt, presentation/src/main/java/com/woowahan/ordering/ui/viewmodel/CartViewModel.kt, presentation/src/main/res/values/strings.xml
- 장바구니
- close #162 
- 실패 시 토스트 메시지
=> [FIX] #162 - 장바구니 성공/실패 처리

presentation/src/main/java/com/woowahan/ordering/ui/viewmodel/CartBottomSheetViewModel.kt
- 공통
- Flow 관련 코드 수정
- 지우지 못한 Dispatcher 제거
=> [FIX] 필요없는 Dispatcher 제거

domain/src/main/java/com/woowahan/ordering/domain/usecase/food/GetBestListUseCase.kt, domain/src/main/java/com/woowahan/ordering/domain/usecase/food/GetFoodDetailUseCase.kt, domain/src/main/java/com/woowahan/ordering/domain/usecase/food/GetMenuListUseCase.kt, presentation/src/main/java/com/woowahan/ordering/di/usecase/FoodUseCaseModule.kt, presentation/src/main/java/com/woowahan/ordering/ui/viewmodel/BestViewModel.kt, presentation/src/main/java/com/woowahan/ordering/ui/viewmodel/DetailViewModel.kt, presentation/src/main/java/com/woowahan/ordering/ui/viewmodel/MainDishViewModel.kt, presentation/src/main/java/com/woowahan/ordering/ui/viewmodel/OtherDishViewModel.kt
- close #166 
- 유스케이스에 디스패처 주입
- launch 에서 디스패처 제거
=> [REFACTOR] Food UseCase의 Flow 관련 코드 수정

domain/src/main/java/com/woowahan/ordering/domain/usecase/order/GetOrderedCartByDeliveryTimeUseCase.kt, domain/src/main/java/com/woowahan/ordering/domain/usecase/order/GetSimpleOrderUseCase.kt, domain/src/main/java/com/woowahan/ordering/domain/usecase/order/InsertOrderUseCase.kt, domain/src/main/java/com/woowahan/ordering/domain/usecase/order/IsExistNotDeliveredOrderUseCase.kt, domain/src/main/java/com/woowahan/ordering/domain/usecase/order/UpdateOrderUseCase.kt, presentation/src/main/java/com/woowahan/ordering/di/usecase/OrderUseCaseModule.kt, presentation/src/main/java/com/woowahan/ordering/ui/viewmodel/CartViewModel.kt, presentation/src/main/java/com/woowahan/ordering/ui/viewmodel/OrderDetailViewModel.kt, presentation/src/main/java/com/woowahan/ordering/ui/viewmodel/OrderListViewModel.kt, presentation/src/main/java/com/woowahan/ordering/ui/worker/DeliveryTimeWorker.kt
- close #169
- Flow 관련 코드 수정
- flowOn을 UseCase에 추가
- 서버 통신 없이 Hot Observing 중인 함수는 result로 묶지 않은 리스트 반환하기
=> [REFACTOR] #169 - Order UseCase의 Flow 관련 코드 수정

domain/src/main/java/com/woowahan/ordering/domain/usecase/history/GetHistoryUseCase.kt, domain/src/main/java/com/woowahan/ordering/domain/usecase/history/InsertHistoryUseCase.kt, domain/src/main/java/com/woowahan/ordering/domain/usecase/history/UpdateHistoryUseCase.kt, presentation/src/main/java/com/woowahan/ordering/di/usecase/HistoryUseCaseModule.kt, presentation/src/main/java/com/woowahan/ordering/ui/viewmodel/DetailViewModel.kt, presentation/src/main/java/com/woowahan/ordering/ui/viewmodel/HistoryViewModel.kt
- close #170 
- 유스케이스에 디스패처 주입
- launch 에서 디스패처 제거
=> [REFACTOR] #170 - History UseCase의 Flow 관련 코드 수정

presentation/src/main/java/com/woowahan/ordering/ui/receiver/CartReceiver.kt, presentation/src/main/java/com/woowahan/ordering/util/NotificationUtil.kt
- close #176
- Notification 생성하는 클래스 나누기
- NotificationUtil 클래스 만들기
=> [REFACTOR] #176 - Notification 생성하는 클래스 나누기

data/src/main/java/com/woowahan/ordering/data/datasource/HistoryDataSource.kt, data/src/main/java/com/woowahan/ordering/data/local/dao/HistoryDao.kt, data/src/main/java/com/woowahan/ordering/data/local/datasource/HistoryDataSourceImpl.kt, data/src/main/java/com/woowahan/ordering/data/repository/HistoryRepositoryImpl.kt, domain/src/main/java/com/woowahan/ordering/domain/repository/HistoryRepository.kt, domain/src/main/java/com/woowahan/ordering/domain/usecase/history/GetHistoryUseCase.kt, presentation/src/main/java/com/woowahan/ordering/ui/adapter/DiffUtils.kt, presentation/src/main/java/com/woowahan/ordering/ui/adapter/cart/HistoryPagingAdapter.kt, presentation/src/main/java/com/woowahan/ordering/ui/fragment/cart/recently/HistoryFragment.kt, presentation/src/main/java/com/woowahan/ordering/ui/viewmodel/HistoryViewModel.kt
- 최근 본 상품
- close #178
- 페이징 적용
- data layer PagingDataSource 로 변경
- PagingDataAdatper 정의
=> [FIX] #178 - 최근 본 상품 페이징 적용

presentation/src/main/java/com/woowahan/ordering/ui/fragment/order/OrderListFragment.kt, presentation/src/main/java/com/woowahan/ordering/ui/viewmodel/OrderListViewModel.kt, presentation/src/main/res/drawable/ic_baseline_priority_high_24.xml, presentation/src/main/res/layout/fragment_order_list.xml, presentation/src/main/res/layout/layout_no_item.xml, presentation/src/main/res/values/strings.xml
- OrderListFragment
- close #184
- 주문 내역 화면 수정 사항
- Empty뷰 적용
- PagingData 받아오는 flow에 cachedIn 추가
=> [FIX] #184 - 주문 내역 화면 수정 사항

presentation/src/main/java/com/woowahan/ordering/ui/viewmodel/CartViewModel.kt, presentation/src/main/res/layout/item_empty.xml
=> [FIX] #186 - 최근 본 상품 없는 경우 대응

.github/workflows/cd.yml, presentation/build.gradle
- close #192
- 버전 1.0.1 릴리즈
- 패키징 오류 해결
=> [RELEASE] 1.0.1

presentation/src/main/java/com/woowahan/ordering/ui/fragment/home/HomeFragment.kt, presentation/src/main/java/com/woowahan/ordering/ui/fragment/home/best/BestFragment.kt, presentation/src/main/java/com/woowahan/ordering/ui/fragment/home/main/MainDishFragment.kt, presentation/src/main/java/com/woowahan/ordering/ui/fragment/home/other/OtherDishFragment.kt
=> [FIX] 다크모드로 변경 시 상세화면 리스너 초기화 문제 해결

presentation/src/main/java/com/woowahan/ordering/ui/adapter/home/CountAndFilterAdapter.kt, presentation/src/main/java/com/woowahan/ordering/ui/adapter/home/TypeAndFilterAdapter.kt, presentation/src/main/java/com/woowahan/ordering/ui/fragment/home/HomeFragment.kt, presentation/src/main/java/com/woowahan/ordering/ui/fragment/home/main/MainDishFragment.kt, presentation/src/main/java/com/woowahan/ordering/ui/fragment/home/other/OtherDishFragment.kt, presentation/src/main/java/com/woowahan/ordering/ui/viewmodel/MainDishViewModel.kt, presentation/src/main/java/com/woowahan/ordering/ui/viewmodel/OtherDishViewModel.kt
- 홈 화면
- close #202
- 다른 화면에 갔다 왔을 때 필터 상태 저장
- 필터 상태를 뷰모델에 저장
- Flow로 상태 뷰에 반영하기
=> [FIX] #202 - 다른 화면에 갔다 왔을 때 필터 상태 저장

presentation/src/main/java/com/woowahan/ordering/ui/adapter/detail/DetailInfoAdapter.kt, presentation/src/main/java/com/woowahan/ordering/ui/fragment/detail/DetailFragment.kt, presentation/src/main/res/layout/item_detail_images.xml
- DetailFragment
- close #204
- 회전 시 발생하는 이슈 해결
=> [FIX] #204 - 자세히 보기 화면 수정 사항

presentation/src/main/java/com/woowahan/ordering/ui/widget/HorizontalRecyclerView.kt, presentation/src/main/res/layout/fragment_best.xml, presentation/src/main/res/layout/item_food_best.xml
- BestFragment
- close #215
- 기획전 화면에서 RecyclerView 스크롤, ViewPager 스크롤 중첩 이슈
- 헤더와 아이템 간격 늘리기
- HorizontalRecyclerView 커스텀 뷰 추가 및 ItemClickListener 추가
- parent RecyclerView는 일반 RecyclerView로 지정
- 리스트 Margin 조정하기
=> [FIX] #215 - 기획전 화면 수정 사항

presentation/src/main/java/com/woowahan/ordering/ui/fragment/cart/recently/HistoryFragment.kt, presentation/src/main/java/com/woowahan/ordering/util/FragmentReplace.kt
- 상세화면
- close #225 
- 상세화면으로 전환 시 새 인스턴스 생성
=> [FIX] #225 - 상세화면 재진입 시 이전 상품이 유지되는 버그 해결
